package fadlann;

import java.awt.Toolkit;
import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Fadlan Ramadhan
 */
public class Form_mahasiswa extends javax.swing.JFrame {
    
    private void Kosongkan_Form(){
        txtField_npm.setEditable(true);
        txtField_npm.setText(null);
        txtField_nama.setText(null);
        buttonGroup1.clearSelection();
        cmbJurusan.setSelectedItem("");
        txtField_tmptLahir.setText(null);
        txtField_tgLahir.setText(null);
        txtField_alamat.setText(null);
    }
    
    private void TampilData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Npm");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Jurusan");
        model.addColumn("Tempat Lahir");
        model.addColumn("Tanggal lahir");
        model.addColumn("Alamat");
        
        try {
            
            int no = 1;
            
            String sql = "SELECT * FROM tbl_mahasiswa WHERE npm like '%"
                    + textFieldCari.getText() + "%'"
                    + "or nm_mahasiswa like '%" + textFieldCari.getText()+ "%'";;
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1),
                rs.getString(2), rs.getString(3),
                rs.getString(4), rs.getString(5),
                rs.getString(6), rs.getString(7)});
            }
            tableOutput.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    public void reset() {
        txtField_npm.setText("");
        txtField_nama.setText("");
        rbtnLaki.getText();
        rbtnPerempuan.getText();
        cmbJurusan.setSelectedItem("");
        txtField_tmptLahir.setText("");
        txtField_tgLahir.setText("");
        txtField_alamat.setText("");
    }
    
    public Form_mahasiswa() {
        initComponents();
        TampilData();
        Kosongkan_Form();
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tmpt_lahir = new javax.swing.JLabel();
        nik = new javax.swing.JLabel();
        tgl_lahir = new javax.swing.JLabel();
        j_kelamin = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        txtField_nama = new javax.swing.JTextField();
        txtField_tmptLahir = new javax.swing.JTextField();
        txtField_alamat = new javax.swing.JTextField();
        txtField_tgLahir = new javax.swing.JTextField();
        txtField_npm = new javax.swing.JTextField();
        buttonEdit = new java.awt.Button();
        buttonHapus = new java.awt.Button();
        buttonSimpan = new java.awt.Button();
        buttonReset = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        cmbJurusan = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOutput = new javax.swing.JTable();
        rbtnLaki = new javax.swing.JRadioButton();
        rbtnPerempuan = new javax.swing.JRadioButton();
        textFieldCari = new javax.swing.JTextField();
        btnCari = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nama ");

        tmpt_lahir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tmpt_lahir.setText("Tempat Lahir");

        nik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nik.setText("NPM");

        tgl_lahir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tgl_lahir.setText("Tanggal Lahir");

        j_kelamin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j_kelamin.setText("Jenis Kelamin");

        alamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alamat.setText("Alamat");

        txtField_tgLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_tgLahirActionPerformed(evt);
            }
        });

        txtField_npm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_npmActionPerformed(evt);
            }
        });

        buttonEdit.setBackground(new java.awt.Color(153, 204, 255));
        buttonEdit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonEdit.setLabel("EDIT");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonHapus.setActionCommand("CANCEL");
        buttonHapus.setBackground(new java.awt.Color(255, 0, 0));
        buttonHapus.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonHapus.setLabel("DELETE");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonSimpan.setBackground(new java.awt.Color(51, 204, 0));
        buttonSimpan.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonSimpan.setLabel("SIMPAN");
        buttonSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSimpanMouseClicked(evt);
            }
        });
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonReset.setBackground(new java.awt.Color(255, 255, 51));
        buttonReset.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonReset.setLabel("RESET");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Jurusan");

        cmbJurusan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- LIST JURUSAN -", "Teknik Informatika", "Sistem Informasi", "Manajemen Informatika", "Akuntansi" }));
        cmbJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJurusanActionPerformed(evt);
            }
        });

        tableOutput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableOutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Npm", "Nama", "Jenis Kelamin", "Jurusan", "Tempat Lahir", "Tgl Lahir", "Alamat"
            }
        ));
        tableOutput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOutputMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableOutput);

        buttonGroup1.add(rbtnLaki);
        rbtnLaki.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        rbtnLaki.setText("Laki - Laki");
        rbtnLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnLakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnPerempuan);
        rbtnPerempuan.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        rbtnPerempuan.setText("Perempuan");
        rbtnPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPerempuanActionPerformed(evt);
            }
        });

        textFieldCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCariActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnCari.setLabel("Search");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label1.setText("FORM DATA MAHASISWA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 570, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tgl_lahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(tmpt_lahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j_kelamin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbtnPerempuan)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(txtField_npm)
                                    .addComponent(txtField_nama)
                                    .addComponent(cmbJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtField_tmptLahir)
                                    .addComponent(txtField_tgLahir)
                                    .addComponent(txtField_alamat, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_npm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nik))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnPerempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_tmptLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmpt_lahir))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_tgLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl_lahir))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        try {
            String sql = "DELETE FROM tbl_mahasiswa WHERE npm ='" + txtField_npm.getText() + "'";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DIHAPUS");
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        TampilData();
        Kosongkan_Form();
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
       
        String jenis_kelamin = null;
        if (rbtnLaki.isSelected()){
            jenis_kelamin = "Laki-Laki";
        }else if (rbtnPerempuan.isSelected()) {
            jenis_kelamin = "Perempuan";
        }
        
        try {
            String sql = "INSERT INTO tbl_mahasiswa VALUES ('" + txtField_npm.getText()
                    + "','" + txtField_nama.getText()
                    + "','" + jenis_kelamin 
                    + "','" + cmbJurusan.getSelectedItem()
                    + "','" + txtField_tmptLahir.getText()
                    + "','" + txtField_tgLahir.getText()
                    + "','" + txtField_alamat.getText() + "')";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN");
            TampilData();
            Kosongkan_Form();
            
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
    }//GEN-LAST:event_buttonSimpanActionPerformed

    
    private void cmbJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJurusanActionPerformed

    private void txtField_tgLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_tgLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_tgLahirActionPerformed

    private void rbtnLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnLakiActionPerformed

    private void rbtnPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnPerempuanActionPerformed

    private void tableOutputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOutputMouseClicked
        int baris = tableOutput.rowAtPoint(evt.getPoint());
        
        String kode = tableOutput.getValueAt(baris, 1).toString();
        txtField_npm.setText(kode);
        
        String nama = tableOutput.getValueAt(baris, 2).toString();
        txtField_nama.setText(nama);
        
        if("Perempuan".equals(tableOutput.getValueAt(baris, 3).toString())){
            rbtnPerempuan.setSelected(true);
        }else {
            rbtnLaki.setSelected(true);
        }
        
        String jurusan = tableOutput.getValueAt(baris, 4).toString();
        cmbJurusan.setSelectedItem(jurusan);
        
        String tempat = tableOutput.getValueAt(baris, 5).toString();
        txtField_tmptLahir.setText(tempat);
        
        String tanggal = tableOutput.getValueAt(baris, 6).toString();
        txtField_tgLahir.setText(tanggal);
        
        String domisili = tableOutput.getValueAt(baris, 7).toString();
        txtField_alamat.setText(domisili);
    }//GEN-LAST:event_tableOutputMouseClicked

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
       reset();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
 
        try {
            String sql = "UPDATE tbl_mahasiswa SET npm ='" + txtField_npm.getText()
                    + "',nm_mahasiswa='" + txtField_nama.getText()
                    + "',jurusan='" + cmbJurusan.getSelectedItem()
                    + "',tempat='" + txtField_tmptLahir.getText()
                    + "',tgl='" + txtField_tgLahir.getText()
                    + "',alamat='" + txtField_alamat.getText()
                    + "' WHERE npm = '" + txtField_npm.getText() + "'";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "EDIT DATA BERHASIL");
        }catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        TampilData();
        Kosongkan_Form();
    }//GEN-LAST:event_buttonEditActionPerformed

    private void txtField_npmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_npmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_npmActionPerformed

    private void buttonSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSimpanMouseClicked
        
        
    }//GEN-LAST:event_buttonSimpanMouseClicked

    private void textFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCariActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try {
            String sql = "SELECT * FROM tbl_mahasiswa WHERE npm like '%"
                    + textFieldCari.getText() + "%'"
                    + "or nm_mahasiswa like '%" + textFieldCari.getText();
            
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            
        }catch (HeadlessException | SQLException e){
            
        }
        TampilData();
        Kosongkan_Form();
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private java.awt.Button btnCari;
    private java.awt.Button buttonEdit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private java.awt.Button buttonHapus;
    private java.awt.Button buttonReset;
    private java.awt.Button buttonSimpan;
    private javax.swing.JComboBox<String> cmbJurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel j_kelamin;
    private java.awt.Label label1;
    private javax.swing.JLabel nik;
    private javax.swing.JRadioButton rbtnLaki;
    private javax.swing.JRadioButton rbtnPerempuan;
    private javax.swing.JTable tableOutput;
    private javax.swing.JTextField textFieldCari;
    private javax.swing.JLabel tgl_lahir;
    private javax.swing.JLabel tmpt_lahir;
    private javax.swing.JTextField txtField_alamat;
    private javax.swing.JTextField txtField_nama;
    private javax.swing.JTextField txtField_npm;
    private javax.swing.JTextField txtField_tgLahir;
    private javax.swing.JTextField txtField_tmptLahir;
    // End of variables declaration//GEN-END:variables

}
